<a href="https://colab.research.google.com/github/Cpsbd66/Pytorch-Journey/blob/main/Chapter%200%20%E2%80%93%20PyTorch%20Fundamentals/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to tensers

### Creating tensors

In [ ]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
# Get tensor back as Python int
scaler.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5],
                        [1, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [1, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape # 1, 3 by 3 tensor = [1, 3, 3]

torch.Size([1, 4, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors
Why random tensors ?
Random tensors are important because the way many neural networks learn is that they start with full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> Look at data -> Update random numbers -> Look at data -> Update`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5443, 0.9369, 0.3771, 0.3134],
        [0.8677, 0.8680, 0.7792, 0.2600],
        [0.8625, 0.6499, 0.8616, 0.9694]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3)) #height, width, color channel(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 bug errors you'll run into with Pytorch & deep learning
1. Tensorts not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor is (eg. float 32, float16)
                               Device = "cuda", # what device is your tensor on
                               requires_grad = False) # wheter or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (Tensor attributes)

1. Tensorts not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2847, 0.9994, 0.3636, 0.9087],
        [0.2835, 0.6525, 0.5978, 0.3192],
        [0.9456, 0.2872, 0.8861, 0.5862]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2847, 0.9994, 0.3636, 0.9087],
        [0.2835, 0.6525, 0.5978, 0.3192],
        [0.9456, 0.2872, 0.8861, 0.5862]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication